# import = ["/Users/kyle/.config/alacritty/catppuccin-macchiato.toml"]
import = ["/Users/kyle/.config/alacritty/catppuccin-frappe.toml"]

[env]
  TERM = "alacritty"
  


[font]
size = 17

[font.normal]
family = "FiraCode Nerd Font"

[window]


    padding = {x = 10 , y = 10}
  
    decorations = "buttonless"

    opacity = 1.0

    startup_mode = "Windowed"

    dynamic_padding = true

[selection]
  
  save_to_clipboard = true


