# import = ["/Users/kyle/.config/alacritty/catppuccin-macchiato.toml"]
# import = ["/Users/kyle/.config/alacritty/catppuccin-frappe.toml"]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/base16_default_dark.toml"
  "~/.config/alacritty/aura.toml"
  # "~/.config/alacritty/blood_moon.toml"
  # "~/.config/alacritty/ashes_dark.toml"
]

[env]
  TERM = "xterm-256color"
  


[font]
size = 17

[font.normal]
family = "FiraCode Nerd Font"

[window]


    padding = {x = 12, y = 12}
  
    decorations = "buttonless"

    opacity = 0.8

    blur = true

    startup_mode = "Windowed"

    dynamic_padding = true

[selection]
  
  save_to_clipboard = true

[cursor]
  style = "Block"
  # cursor_style = "BlinkingBeam"
  # blinking = true
  
  unfocused_hollow = false
  
  thickness = 0.15

  # animated = true

  blink_interval = 500
  

  

# key bind for slelect all the text 
# [key_bindings]
#   { key = "A" , mods = "Control|Shift", action = "SelectAll"}


