return {
  {
    "nvim-treesitter/nvim-treesitter",
    tag = "v0.9.1",
    opts = {
      ensure_installed = {
        "javascript",
        "typescript",
        "css",
        "gitignore",
        "graphql",
        "http",
        "json",
        "scss",
        "sql",
        "vim",
        "lua",
        "c",
        "cpp",
        "ninja",
        "python",
        "rst",
        "toml",
        "svelte",
        "go",
        -- "prisma",
        "swift",
        "cmake",
        "fish",
        "astro",
        "php",
        "java",
        "gitignore",
      },
      query_linter = {
        enable = true,
        use_virtual_text = true,
        lint_events = { "BufWrite", "CursorHold" },
      },
    },
  },
}
